
KEA_MSG_COMPILER ?= kea-msg-compiler
KEA_INCLUDE ?= /usr/include/kea
KEA_LIB ?= /usr/lib

OBJECTS = src/messages.o src/logger.o src/load.o src/runscript.o src/callouts.o src/version.o
CXXFLAGS = -I $(KEA_INCLUDE) -fPIC -Wno-deprecated -std=c++11
LDFLAGS = -L $(KEA_LIB) -shared -lkea-dhcpsrv -lkea-dhcp++ -lkea-hooks -lkea-log -lkea-util -lkea-exceptions

kea-hook-runscript.so: $(OBJECTS)
	$(CXX) -o $@ $(CXXFLAGS) $(LDFLAGS) $(OBJECTS)

%.o: %.cc src/messages.h src/messages.mes
	$(CXX) -c $(CXXFLAGS) -o $@ $<

# Compile messages (for logging)
# Both .h and .cc are generated by kea-msg-compiler, but this
# can't be expressed directly in a Makefile.
src/messages.h: src/messages.cc

src/messages.cc: src/messages.mes
	$(KEA_MSG_COMPILER) -d src/ $<

clean:
	rm -f src/*.o
	rm -f src/messages.h src/messages.cc
	rm -f kea-hook-runscript.so
